# Configuração SonarQube - projeto kafka-pedidos
sonar.projectKey=kafka-pedidos
sonar.projectName=kafka-pedidos

sonar.web.host=0.0.0.0
sonar.web.port=9000

sonar.log.level=INFO

# Banco embarcado para ambiente de estudo (avaliacao)
# Para producao utilizar PostgreSQL externo

sonar.core.serverBaseURL=http://localhost:9000

# Integracao JaCoCo (configurada nos microsservicos)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.java.source=21
